import { StyleSheet, Platform } from 'react-native';
import {
  colors,
  fontSize,
  borderRadius,
  spaceVertical,
  marginHorizontal,
  fontFamily,
  btnHeight,
  responsiveWidth,
  responsiveHeight,
} from '../../../styles/variables';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: marginHorizontal.small,
    paddingVertical: Platform.OS === 'ios' ? spaceVertical.normal : spaceVertical.small,
  },
  modalCard: {
    backgroundColor: colors.cardBackground,
    borderRadius: borderRadius.cardRadius,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: marginHorizontal.small,
    paddingTop: spaceVertical.semiSmall,
    paddingBottom: spaceVertical.semiSmall,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.45,
    shadowRadius: 20,
    elevation: 10,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spaceVertical.tiny,
  },
  headerTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  warningIconContainer: {
    width: responsiveWidth(8),
    height: responsiveWidth(8),
    borderRadius: responsiveWidth(4),
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: marginHorizontal.extraSmall,
  },
  warningIconText: {
    fontSize: fontSize.medium,
    color: '#F59E0B',
    fontWeight: '800',
  },
  headerTitle: {
    fontSize: fontSize.medium,
    fontWeight: '700',
    color: '#F59E0B',
    fontFamily: fontFamily.bold,
  },
  closeButton: {
    width: responsiveWidth(8),
    height: responsiveWidth(8),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: responsiveWidth(4),
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
  },
  closeButtonText: {
    fontSize: fontSize.medium,
    color: colors.subtitleColor,
    fontWeight: '600',
    lineHeight: fontSize.medium + 2,
  },
  subtitle: {
    fontSize: fontSize.extraSmall,
    color: colors.subtitleColor,
    fontWeight: '400',
    lineHeight: 18,
    marginTop: spaceVertical.tinySamll,
    marginBottom: spaceVertical.small,
    fontFamily: fontFamily.regular,
  },
  deviceListContainer: {
    marginBottom: spaceVertical.small,
    gap: spaceVertical.tinySamll + 2,
  },
  deviceItemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBackground,
    borderWidth: 1.5,
    borderColor: colors.inputBorder,
    borderRadius: borderRadius.medium,
    paddingHorizontal: marginHorizontal.small,
    paddingVertical: spaceVertical.tiny,
  },
  deviceItemCardSelected: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(147, 51, 234, 0.14)',
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.iconDefault,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: marginHorizontal.small,
  },
  radioOuterSelected: {
    borderColor: colors.primary,
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },
  deviceInfoContainer: {
    flex: 1,
  },
  deviceName: {
    fontSize: fontSize.small,
    fontWeight: '700',
    color: colors.white,
    fontFamily: fontFamily.bold,
    marginBottom: 2,
  },
  deviceDate: {
    fontSize: fontSize.extraSmall - 1,
    color: colors.labelColor,
    fontFamily: fontFamily.regular,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spaceVertical.tinySamll,
    gap: marginHorizontal.extraSmall,
  },
  cancelButton: {
    flex: 1,
    height: 44,
    borderRadius: borderRadius.btnRadius,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    fontSize: fontSize.small,
    fontWeight: '600',
    color: colors.white,
    fontFamily: fontFamily.medium,
  },
  confirmButton: {
    flex: 1.4,
    height: 44,
    borderRadius: borderRadius.btnRadius,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  confirmButtonDisabled: {
    opacity: 0.45,
    shadowOpacity: 0,
    elevation: 0,
  },
  confirmButtonText: {
    fontSize: fontSize.small,
    fontWeight: '700',
    color: colors.white,
    fontFamily: fontFamily.bold,
  },
});
