import { StyleSheet, Platform } from 'react-native';
import {
  colors,
  fontSize,
  borderRadius,
  spaceVertical,
  marginHorizontal,
  fontFamily,
  btnHeight,
  responsiveWidth,
  responsiveHeight,
} from '../../../styles/variables';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    paddingHorizontal: marginHorizontal.small,
    paddingTop: spaceVertical.large,
    paddingBottom: 80,
  },
  headerContainer: {
    alignItems: 'center',
    marginBottom: spaceVertical.semiSmall,
  },
  lockIconCircle: {
    width: responsiveWidth(16),
    height: responsiveWidth(16),
    borderRadius: responsiveWidth(8),
    backgroundColor: 'rgba(147, 51, 234, 0.15)',
    borderWidth: 1.5,
    borderColor: 'rgba(147, 51, 234, 0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spaceVertical.small,
  },
  lockIcon: {
    width: responsiveWidth(8),
    height: responsiveWidth(8),
    tintColor: colors.primaryLight,
  },
  title: {
    fontSize: fontSize.large,
    fontWeight: '800',
    color: colors.titleColor,
    letterSpacing: -0.3,
    textAlign: 'center',
    marginBottom: spaceVertical.tinySamll,
    fontFamily: fontFamily.bold,
  },
  subtitle: {
    fontSize: fontSize.extraSmall,
    color: colors.subtitleColor,
    textAlign: 'center',
    fontWeight: '400',
    lineHeight: 18,
    paddingHorizontal: marginHorizontal.small,
    fontFamily: fontFamily.regular,
  },
  card: {
    backgroundColor: colors.cardBackground,
    borderRadius: borderRadius.cardRadius,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: marginHorizontal.small,
    paddingTop: spaceVertical.semiSmall,
    paddingBottom: spaceVertical.small,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.45,
    shadowRadius: 20,
    elevation: 10,
  },
  inputIcon: {
    width: responsiveHeight(2.5),
    height: responsiveHeight(2.5),
  },
  helperText: {
    fontSize: fontSize.extraSmall - 1,
    color: colors.labelColor,
    marginTop: -spaceVertical.tinySamll + 2,
    marginBottom: spaceVertical.small,
    marginLeft: marginHorizontal.smallest,
    fontFamily: fontFamily.regular,
  },
  submitButton: {
    marginTop: spaceVertical.tinySamll,
    height: btnHeight,
    borderRadius: borderRadius.btnRadius,
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.5,
    shadowRadius: 14,
    elevation: 8,
  },
  submitButtonText: {
    fontSize: fontSize.normal,
    fontWeight: '700',
    color: colors.white,
    fontFamily: fontFamily.bold,
  },
  backToLoginButton: {
    marginTop: spaceVertical.small,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spaceVertical.tiny,
  },
  backToLoginText: {
    color: colors.subtitleColor,
    fontSize: fontSize.small,
    fontWeight: '600',
    fontFamily: fontFamily.medium,
  },
});
