import { StyleSheet, Platform } from 'react-native';
import {
  colors,
  fontFamily,
  fontSize,
  marginHorizontal,
  responsiveHeight,
  responsiveWidth,
  borderRadius,
  spaceVertical,
} from '../../../styles/variables';

const HEADER_VERTICAL_PADDING = responsiveHeight(1.6);
const AVATAR_SIZE = responsiveWidth(10.5);

const styles = StyleSheet.create({
  /* ── Safe Area ── */
  safeArea: {
    flex: 1,
    backgroundColor: colors.white,
  },

  /* ── Top Header ── */
  header: {
    backgroundColor: colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: marginHorizontal.small,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF2F6',
    ...Platform.select({
      android: {
        elevation: 2,
      },
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 3,
      },
    }),
  },

  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },

  headerLogo: {
    width: responsiveWidth(32),
    height: responsiveWidth(9.5),
  },

  profileChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    paddingLeft: 10,
    paddingRight: 8,
    paddingVertical: 4,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 6,
    flexShrink: 1,
    marginLeft: 8,
  },
  profileDownArrow: {
    width: 10,
    height: 10,
    tintColor: '#94A3B8',
    marginLeft: 1,
  },

  avatarWrapper: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
  },
  avatarLetter: {
    fontSize: 13,
    fontFamily: fontFamily.bold,
    color: colors.white,
    textAlign: 'center',
    textAlignVertical: 'center',
    includeFontPadding: false,
  },

  userInfo: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-end',
    flexShrink: 1,
  },
  userName: {
    fontSize: 12,
    fontFamily: fontFamily.bold,
    color: '#0F172A',
    letterSpacing: 0.1,
    textAlign: 'right',
  },
  userRole: {
    fontSize: 10,
    fontFamily: fontFamily.medium,
    color: '#64748B',
    marginTop: 1,
    textTransform: 'capitalize',
    textAlign: 'right',
  },

  notificationBtn: {
    width: responsiveWidth(10),
    height: responsiveWidth(10),
    borderRadius: responsiveWidth(10) / 2,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationIcon: {
    width: responsiveWidth(4.5),
    height: responsiveWidth(4.5),
    tintColor: '#0F172A',
  },
  notificationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#EF4444',
    position: 'absolute',
    top: 6,
    right: 6,
    borderWidth: 1.5,
    borderColor: colors.white,
  },

  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 10,
    flex: 1,
    marginLeft: 12,
  },

  logoutBtn: {
    width: responsiveWidth(9),
    height: responsiveWidth(9),
    borderRadius: responsiveWidth(9) / 2,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  logoutIcon: {
    fontSize: responsiveWidth(4.8),
    color: colors.white,
    lineHeight: responsiveWidth(6),
  },

  /* ── Logout Confirmation Modal ── */
  logoutModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 28,
  },
  logoutModalCard: {
    width: '100%',
    maxWidth: 320,
    backgroundColor: colors.white,
    borderRadius: 24,
    paddingHorizontal: 24,
    paddingVertical: 28,
    alignItems: 'center',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 16,
    elevation: 10,
  },
  logoutModalIconWrap: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#FEF2F2',
    borderWidth: 1.5,
    borderColor: '#FECACA',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  logoutModalIcon: {
    fontSize: 26,
    color: '#DC2626',
    lineHeight: 32,
  },
  logoutModalTitle: {
    fontSize: 18,
    fontFamily: fontFamily.bold,
    color: '#0F172A',
    marginBottom: 8,
  },
  logoutModalSubtitle: {
    fontSize: 13.5,
    fontFamily: fontFamily.regular,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },
  logoutModalBtns: {
    flexDirection: 'row',
    width: '100%',
    gap: 10,
  },
  logoutCancelBtn: {
    flex: 1,
    height: 46,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutCancelText: {
    fontSize: 14,
    fontFamily: fontFamily.bold,
    color: '#475569',
  },
  logoutConfirmBtn: {
    flex: 1,
    height: 46,
    borderRadius: 14,
    backgroundColor: '#DC2626',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#DC2626',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  logoutConfirmText: {
    fontSize: 14,
    fontFamily: fontFamily.bold,
    color: colors.white,
  },

  /* ── Active Alert Popup Modal ── */
  alertPopupOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.62)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 22,
  },
  alertPopupCard: {
    width: '100%',
    maxWidth: 340,
    backgroundColor: colors.white,
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 18,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 20,
    elevation: 12,
  },
  alertPopupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
    gap: 10,
  },
  alertPopupBadge: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#FAF5FF',
    borderWidth: 1.5,
    borderColor: '#DDD6FE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  alertPopupBadgeText: {
    fontSize: 18,
    lineHeight: 24,
  },
  alertPopupHeading: {
    fontSize: 15,
    fontFamily: fontFamily.bold,
    color: '#0F172A',
  },
  alertPopupCounter: {
    fontSize: 11.5,
    fontFamily: fontFamily.regular,
    color: '#94A3B8',
    marginTop: 1,
  },
  alertPopupClose: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  alertPopupCloseText: {
    fontSize: 12,
    color: '#64748B',
    fontFamily: fontFamily.bold,
  },
  alertPopupImageWrap: {
    width: '100%',
    height: 160,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#FAF5FF',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#EDE9FE',
  },
  alertPopupImage: {
    width: '100%',
    height: '100%',
  },
  alertPopupTitle: {
    fontSize: 15.5,
    fontFamily: fontFamily.bold,
    color: '#0F172A',
    lineHeight: 21,
    marginBottom: 6,
  },
  alertPopupDesc: {
    fontSize: 13,
    fontFamily: fontFamily.regular,
    color: '#475569',
    lineHeight: 19,
    marginBottom: 16,
  },
  alertPopupActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 4,
  },
  alertPopupNavBtn: {
    paddingVertical: 9,
    paddingHorizontal: 18,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
  },
  alertPopupNavText: {
    fontSize: 13,
    fontFamily: fontFamily.bold,
    color: '#475569',
  },
  alertPopupNextBtn: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  alertPopupNextText: {
    fontSize: 13,
    fontFamily: fontFamily.bold,
    color: colors.white,
  },

  /* ── Active Offers Auto-Scrolling Ticker Bar ── */
  tickerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#7C3AED',
    height: 38,
    paddingHorizontal: 12,
    overflow: 'hidden',
  },
  tickerBadge: {
    backgroundColor: '#F59E0B',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    marginRight: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  tickerBadgeText: {
    fontSize: 10,
    fontFamily: fontFamily.bold,
    color: '#0F172A',
    letterSpacing: 0.4,
  },
  tickerScroll: {
    flex: 1,
    height: '100%',
  },
  tickerContent: {
    alignItems: 'center',
    paddingRight: 40,
  },
  tickerText: {
    fontSize: 12.5,
    fontFamily: fontFamily.bold,
    color: '#FFFFFF',
    marginRight: 16,
  },

  /* ── Body ── */
  body: {
    flex: 1,
    backgroundColor: colors.primary,
    // borderTopLeftRadius: borderRadius.cardRadius || 24,
    // borderTopRightRadius: borderRadius.cardRadius || 24,
    paddingTop: spaceVertical.extraSmall,
    overflow: 'hidden',
  },

  /* ── Toggle Switch Container ── */
  toggleContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    borderRadius: 14,
    padding: 4,
    marginHorizontal: marginHorizontal.small,
    marginBottom: spaceVertical.extraSmall,
  },
  toggleBtn: {
    flex: 1,
    paddingVertical: responsiveHeight(1.1),
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleBtnActive: {
    backgroundColor: colors.white,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  toggleBtnText: {
    fontSize: fontSize.extraSmall || 12,
    fontFamily: fontFamily.medium,
    color: colors.white,
    textAlign: 'center',
  },
  toggleBtnTextActive: {
    color: colors.primary,
    fontFamily: fontFamily.bold,
  },

  /* ── Filter Bar (Search ABM + State Dropdown) ── */
  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: marginHorizontal.small,
    marginBottom: spaceVertical.small,
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 10,
    height: 42,
    marginRight: 8,
  },
  searchIcon: {
    width: 16,
    height: 16,
    tintColor: '#64748B',
    marginRight: 6,
  },
  searchInput: {
    flex: 1,
    height: '100%',
    fontSize: 13,
    fontFamily: fontFamily.medium,
    color: '#0F172A',
    paddingVertical: Platform.OS === 'ios' ? 8 : 4,
    paddingHorizontal: 4,
  },
  clearSearchBtn: {
    padding: 4,
  },
  clearSearchText: {
    fontSize: 12,
    color: '#94A3B8',
    fontFamily: fontFamily.bold,
  },
  stateDropdownBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FAF5FF',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#DDD6FE',
    paddingHorizontal: 12,
    height: 42,
    minWidth: 110,
    maxWidth: 160,
  },
  stateDropdownBtnActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  stateDropdownText: {
    fontSize: 12,
    fontFamily: fontFamily.bold,
    color: colors.primary,
    flex: 1,
    marginRight: 6,
  },
  stateDropdownTextActive: {
    color: colors.white,
  },
  stateDropdownIcon: {
    width: 12,
    height: 12,
    tintColor: colors.primary,
  },
  stateDropdownIconActive: {
    tintColor: colors.white,
  },

  /* ── Modal Styles for State Picker ── */
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  modalCard: {
    width: '100%',
    maxHeight: '65%',
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 18,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  modalTitle: {
    fontSize: 16,
    fontFamily: fontFamily.bold,
    color: '#0F172A',
  },
  modalCloseBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCloseText: {
    fontSize: 13,
    fontFamily: fontFamily.bold,
    color: '#64748B',
  },
  stateOptionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginBottom: 6,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  stateOptionItemActive: {
    backgroundColor: '#F3E8FF',
    borderColor: '#C084FC',
  },
  stateOptionText: {
    fontSize: 13.5,
    fontFamily: fontFamily.medium,
    color: '#334155',
    flex: 1,
  },
  stateOptionTextActive: {
    color: colors.primary,
    fontFamily: fontFamily.bold,
  },
  selectedCheckBadge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  selectedCheckText: {
    color: colors.white,
    fontSize: 12,
    fontFamily: fontFamily.bold,
  },

  /* ── Brand Wise Filter Dual Controls (State + Date) ── */
  brandFilterControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: marginHorizontal.small,
    marginBottom: spaceVertical.small,
  },
  brandStateDropdownBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FAF5FF',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#DDD6FE',
    paddingHorizontal: 10,
    height: 42,
    marginRight: 8,
  },
  datePickerBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FDF4',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#BBF7D0',
    paddingHorizontal: 10,
    height: 42,
  },
  datePickerBtnActive: {
    backgroundColor: '#059669',
    borderColor: '#059669',
    shadowColor: '#059669',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  datePickerText: {
    fontSize: 12,
    fontFamily: fontFamily.bold,
    color: '#059669',
    flex: 1,
    marginLeft: 6,
  },
  datePickerTextActive: {
    color: colors.white,
  },
  datePickerIcon: {
    width: 14,
    height: 14,
    tintColor: '#059669',
  },
  datePickerIconActive: {
    tintColor: colors.white,
  },

  /* ── Calendar Modal Styles ── */
  calendarCard: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: 22,
    padding: 18,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  calendarNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  calendarNavBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarNavBtnText: {
    fontSize: 16,
    fontFamily: fontFamily.bold,
    color: '#334155',
  },
  calendarMonthText: {
    fontSize: 16,
    fontFamily: fontFamily.bold,
    color: '#0F172A',
  },
  calendarWeekHeader: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 8,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  calendarWeekDayText: {
    width: 36,
    textAlign: 'center',
    fontSize: 12,
    fontFamily: fontFamily.bold,
    color: '#64748B',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
  },
  calendarDayCell: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 3,
  },
  calendarDayCellSelected: {
    backgroundColor: colors.primary,
  },
  calendarDayCellToday: {
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  calendarDayText: {
    fontSize: 13,
    fontFamily: fontFamily.medium,
    color: '#1E293B',
  },
  calendarDayTextSelected: {
    color: colors.white,
    fontFamily: fontFamily.bold,
  },
  calendarDayTextToday: {
    color: colors.primary,
    fontFamily: fontFamily.bold,
  },
  calendarDayTextDisabled: {
    color: '#CBD5E1',
  },
  calendarActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  calendarActionBtn: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
  },
  calendarActionBtnPrimary: {
    backgroundColor: colors.primary,
  },
  calendarActionText: {
    fontSize: 12.5,
    fontFamily: fontFamily.bold,
    color: '#475569',
  },
  calendarActionTextPrimary: {
    color: colors.white,
  },

  /* ── Shared Card List Scroll ── */
  cardListScroll: {
    flex: 1,
    paddingHorizontal: marginHorizontal.small,
  },
  cardListContent: {
    paddingBottom: 120,
  },

  /* ── ABM Cash Deposit Card ── */
  abmCard: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#EDE9FE',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  abmCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    marginBottom: 10,
  },
  abmHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 8,
  },
  abmAvatarBadge: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#F3E8FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  abmAvatarText: {
    fontSize: 13,
    fontFamily: fontFamily.bold,
    color: colors.primary,
  },
  abmNameText: {
    fontSize: 13.5,
    fontFamily: fontFamily.bold,
    color: '#0F172A',
    flex: 1,
  },
  abmPercentBadge: {
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 8,
    paddingVertical: 3.5,
    borderRadius: 12,
    borderWidth: 0.5,
    borderColor: '#86EFAC',
  },
  abmPercentText: {
    fontSize: 11,
    color: '#16A34A',
    fontFamily: fontFamily.bold,
  },

  /* ABM Card 4-Grid */
  abmStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  abmStatItem: {
    width: '48.5%',
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 8,
    marginBottom: 7,
    alignItems: 'center',
  },
  abmStatItemPendingRed: {
    backgroundColor: '#FFF1F2',
    borderWidth: 1,
    borderColor: '#FECDD3',
  },
  abmStatItemPendingGreen: {
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  abmStatLabel: {
    fontSize: 10,
    fontFamily: fontFamily.medium,
    color: '#64748B',
    marginBottom: 2,
    textAlign: 'center',
  },
  abmStatLabelRed: {
    fontSize: 10,
    fontFamily: fontFamily.bold,
    color: '#E11D48',
    marginBottom: 2,
    textAlign: 'center',
  },
  abmStatLabelGreen: {
    fontSize: 10,
    fontFamily: fontFamily.bold,
    color: '#16A34A',
    marginBottom: 2,
    textAlign: 'center',
  },
  abmStatValue: {
    fontSize: 12,
    fontFamily: fontFamily.bold,
    color: '#1E293B',
    textAlign: 'center',
  },
  abmStatValueRed: {
    fontSize: 12,
    fontFamily: fontFamily.bold,
    color: '#E11D48',
    textAlign: 'center',
  },
  abmStatValueGreen: {
    fontSize: 12,
    fontFamily: fontFamily.bold,
    color: '#16A34A',
    textAlign: 'center',
  },

  /* ── Brand Wise Sales Card UI ── */
  totalBrandCard: {
    backgroundColor: '#FAF5FF',
    borderRadius: 18,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1.5,
    borderColor: '#C084FC',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  totalBrandCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E9D5FF',
    marginBottom: 10,
  },
  totalBrandHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  totalBrandIconWrapper: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  totalBrandProductIcon: {
    width: 18,
    height: 18,
    tintColor: colors.white,
  },
  totalBrandTitle: {
    fontSize: 15,
    fontFamily: fontFamily.bold,
    color: '#4C1D95',
  },
  totalBrandSubtitle: {
    fontSize: 11,
    fontFamily: fontFamily.medium,
    color: '#7C3AED',
  },
  totalBadge: {
    backgroundColor: colors.primary,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  totalBadgeText: {
    fontSize: 10,
    fontFamily: fontFamily.bold,
    color: colors.white,
    letterSpacing: 0.5,
  },
  totalBox: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E9D5FF',
  },
  totalBoxTitle: {
    color: '#6B21A8',
  },
  totalQtyBadge: {
    backgroundColor: '#F3E8FF',
  },
  totalBoxValueText: {
    color: '#1E1B4B',
  },
  totalBoxMtd: {
    backgroundColor: '#FFFFFF',
    borderColor: colors.primary,
    borderWidth: 1.5,
  },
  totalBoxTitleMtd: {
    color: colors.primary,
    fontFamily: fontFamily.bold,
  },
  totalQtyBadgeMtd: {
    backgroundColor: '#EDE9FE',
  },
  totalBoxValueTextMtd: {
    color: colors.primary,
    fontFamily: fontFamily.bold,
  },

  brandCard: {
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#EDE9FE',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
  brandCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    marginBottom: 10,
  },
  brandHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  brandIconWrapper: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#F3E8FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#E9D5FF',
  },
  brandProductIcon: {
    width: 17,
    height: 17,
    tintColor: colors.primary,
  },
  brandHeaderTitleWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandNameText: {
    fontSize: 15,
    fontFamily: fontFamily.bold,
    color: '#0F172A',
    flex: 1,
    marginRight: 8,
  },
  brandIndexBadge: {
    fontSize: 11,
    fontFamily: fontFamily.bold,
    color: '#64748B',
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 0.5,
    borderColor: '#E2E8F0',
  },

  /* Brand 4-Box Metrics Grid (FTD, LMFTD, MTD, LMTD) */
  brandStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  brandBox: {
    width: '48.5%',
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    paddingVertical: 9,
    paddingHorizontal: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  brandBoxMtd: {
    backgroundColor: '#FAF5FF',
    borderColor: '#DDD6FE',
    borderWidth: 1.5,
  },
  brandBoxHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  brandBoxTitle: {
    fontSize: 11,
    fontFamily: fontFamily.bold,
    color: '#64748B',
    textTransform: 'uppercase',
  },
  brandBoxTitleMtd: {
    color: colors.primary,
  },
  brandBoxQtyBadge: {
    backgroundColor: '#E2E8F0',
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 6,
  },
  brandBoxQtyBadgeMtd: {
    backgroundColor: '#EDE9FE',
  },
  brandBoxQtyText: {
    fontSize: 10.5,
    fontFamily: fontFamily.bold,
    color: '#475569',
  },
  brandBoxQtyTextMtd: {
    color: colors.primary,
  },
  brandBoxValueText: {
    fontSize: 12.5,
    fontFamily: fontFamily.bold,
    color: '#0F172A',
    marginTop: 2,
  },
  brandBoxValueTextMtd: {
    color: colors.primary,
  },

  /* Brand Growth Row (Growth Qty % & Growth Value %) */
  brandGrowthRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  brandGrowthBox: {
    width: '48.5%',
    borderRadius: 12,
    paddingVertical: 9,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandGrowthLabel: {
    fontSize: 10.5,
    fontFamily: fontFamily.bold,
    marginBottom: 2,
    textAlign: 'center',
  },
  brandGrowthValue: {
    fontSize: 12.5,
    fontFamily: fontFamily.bold,
    textAlign: 'center',
  },
  growthRedBox: {
    backgroundColor: '#FFF1F2',
    borderWidth: 1,
    borderColor: '#FECDD3',
  },
  growthGreenBox: {
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  growthRedText: {
    color: '#E11D48',
  },
  growthGreenText: {
    color: '#16A34A',
  },

  /* ── Empty & Loading States ── */
  centerLoading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    fontSize: fontSize.small,
    fontFamily: fontFamily.medium,
    color: colors.subtitleColor,
    marginTop: 10,
  },
  emptyContainer: {
    padding: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    fontSize: fontSize.small,
    fontFamily: fontFamily.medium,
    color: colors.subtitleColor,
    textAlign: 'center',
  },
});

export { styles };
export default styles;