import { StyleSheet, Platform } from 'react-native';
import {
  colors,
  fontSize,
  spaceVertical,
  marginHorizontal,
  fontFamily,
  responsiveWidth,
  responsiveHeight,
  borderRadius,
  tabHeight1,
  inputHeight,
} from '../../../styles/variables';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.primary,
  },
  primaryBannerSection: {
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: spaceVertical.normal,
    paddingBottom: spaceVertical.large,
  },
  avatarWrapper: {
    width: responsiveWidth(22),
    height: responsiveWidth(22),
    borderRadius: borderRadius.circle,
    backgroundColor: colors.primaryLight,
    borderWidth: borderRadius.normal,
    borderColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: borderRadius.otpRadius,
    elevation: borderRadius.normal,
  },
  avatarInitial: {
    fontSize: fontSize.XLarge,
    color: colors.white,
    fontFamily: fontFamily.bold,
  },
  profileUserIcon: {
    width: inputHeight,
    height: inputHeight,
    tintColor: colors.white,
  },
  bannerUserName: {
    fontSize: fontSize.medium,
    color: colors.white,
    fontFamily: fontFamily.bold,
    marginTop: spaceVertical.tiny,
    letterSpacing: 0.5,
  },
  bannerUserRole: {
    fontSize: fontSize.extraSmall,
    color: colors.white,
    fontFamily: fontFamily.medium,
    marginTop: spaceVertical.tinySamll,
  },
  detailsCardSection: {
    flex: 1,
    backgroundColor: colors.white,
    borderTopLeftRadius: borderRadius.bigBoxRadius,
    borderTopRightRadius: borderRadius.bigBoxRadius,
    marginTop: -spaceVertical.small,
    overflow: 'hidden',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: borderRadius.semiLarge,
    elevation: borderRadius.otpRadius,
  },
  cardScrollContent: {
    paddingHorizontal: marginHorizontal.normal,
    paddingTop: spaceVertical.normal,
    paddingBottom: tabHeight1,
  },
  infoList: {
    marginBottom: spaceVertical.extraSmall,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: spaceVertical.extraSmall,
  },
  infoLabel: {
    fontSize: fontSize.small,
    color: colors.black,
    fontFamily: fontFamily.extraBold,
    flex: 1,
  },
  infoValue: {
    fontSize: fontSize.small,
    color: colors.black,
    fontFamily: fontFamily.semiBold,
    textAlign: 'right',
    flex: 1.4,
  },
  logoutRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: spaceVertical.small,
    marginTop: spaceVertical.extraSmall,
  },
  logoutText: {
    fontSize: fontSize.small,
    color: colors.error,
    fontFamily: fontFamily.semiBold,
  },
  logoutArrowIcon: {
    width: fontSize.normal,
    height: fontSize.normal,
    tintColor: colors.error,
  },
});