import { StyleSheet } from 'react-native';
import {
  colors,
  fontSize,
  borderRadius,
  spaceVertical,
  marginHorizontal,
  fontFamily,
  btnHeight,
  responsiveWidth,
  responsiveHeight,
} from '../../../styles/variables';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },

  keyboardAvoidingView: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
    width: '100%',
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    paddingHorizontal: marginHorizontal.small,
    paddingTop: spaceVertical.large,
    paddingBottom: 80,
  },
  headerContainer: {
    alignItems: 'center',
    marginBottom: spaceVertical.semiSmall,
  },
  logoWrapper: {
    marginBottom: spaceVertical.small,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: {
    width: responsiveWidth(44),
    height:responsiveWidth(18),
  },
  title: {
    fontSize: fontSize.extraLarge,
    color: colors.titleColor,
    letterSpacing: -0.5,
    textAlign: 'center',
    marginBottom: spaceVertical.tinySamll,
    fontFamily: fontFamily.bold,
  },
  subtitle: {
    fontSize: fontSize.extraSmall,
    color: colors.subtitleColor,
    textAlign: 'center',
    letterSpacing: 0.1,
    fontFamily: fontFamily.regular,
  },
  card: {
    backgroundColor: colors.cardBackground,
    borderRadius: borderRadius.cardRadius,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: marginHorizontal.small,
    paddingTop: spaceVertical.semiSmall,
    paddingBottom: spaceVertical.small,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.45,
    shadowRadius: 20,
    elevation: 10,
  },
  inputIcon: {
    width: responsiveHeight(2.5),
    height: responsiveHeight(2.5),
  },
  buttonIcon: {
    width: responsiveHeight(2),
    height: responsiveHeight(2),
    tintColor: colors.white,
  },
  signInButton: {
    marginTop: spaceVertical.tinySamll,
    height: btnHeight,
    borderRadius: borderRadius.btnRadius,
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.5,
    shadowRadius: 14,
    elevation: 8,
  },
  signInButtonText: {
    fontSize: fontSize.normal,
    color: colors.white,
    fontFamily: fontFamily.bold,
  },
  footerTextContainer: {
    marginTop: spaceVertical.semiSmall,
    alignItems: 'center',
  },
  footerText: {
    color: colors.footerText,
    fontSize: fontSize.extraSmall,
    fontFamily: fontFamily.regular,
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: spaceVertical.small,
  },
  errorBannerIcon: {
    fontSize: 18,
    marginRight: 10,
  },
  errorBannerContent: {
    flex: 1,
  },
  errorBannerTitle: {
    fontSize: 12,
    fontFamily: fontFamily.bold,
    color: '#991B1B',
    marginBottom: 2,
  },
  errorBannerText: {
    fontSize: 11.5,
    fontFamily: fontFamily.medium,
    color: '#DC2626',
    lineHeight: 16,
  },
  errorBannerClose: {
    fontSize: 14,
    color: '#991B1B',
    paddingLeft: 8,
    fontFamily: fontFamily.bold,
  },
  updateCard: {
    marginTop: spaceVertical.semiSmall,
    backgroundColor: colors.cardBackground,
    borderRadius: borderRadius.cardRadius,
    borderWidth: 1,
    borderColor: '#2E2856',
    padding: 14,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  updateCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  updateHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  updateIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#1E1B4B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  updateIcon: {
    fontSize: 18,
  },
  updateHeaderTextWrap: {
    flex: 1,
  },
  updateTitle: {
    fontSize: 13.5,
    fontFamily: fontFamily.bold,
    color: colors.titleColor,
  },
  updateSubtitle: {
    fontSize: 11,
    fontFamily: fontFamily.medium,
    color: colors.subtitleColor,
    marginTop: 1,
  },
  headerUpdateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    gap: 5,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 3,
  },
  headerUpdateBtnIcon: {
    fontSize: 12,
  },
  headerUpdateBtnText: {
    fontSize: 12,
    fontFamily: fontFamily.bold,
    color: colors.white,
    letterSpacing: 0.3,
  },
  updateDivider: {
    height: 1,
    backgroundColor: '#1D2545',
    marginVertical: 12,
  },
  versionCompareRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  versionCardItem: {
    flex: 1,
    backgroundColor: '#090C1B',
    borderWidth: 1,
    borderColor: '#1D2545',
    borderRadius: 10,
    paddingVertical: 9,
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  versionCardItemLatest: {
    backgroundColor: '#1F1338',
    borderColor: '#7C3AED',
  },
  versionCardLabel: {
    fontSize: 9,
    fontFamily: fontFamily.bold,
    color: '#64748B',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  versionCardLabelLatest: {
    fontSize: 9,
    fontFamily: fontFamily.bold,
    color: '#C084FC',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  versionCardNumber: {
    fontSize: 13,
    fontFamily: fontFamily.bold,
    color: '#E2E8F0',
  },
  versionCardNumberLatest: {
    fontSize: 13,
    fontFamily: fontFamily.bold,
    color: '#F3E8FF',
  },
  versionArrowCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#2E1065',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 8,
  },
  versionArrowText: {
    fontSize: 12,
    color: '#C084FC',
    fontWeight: 'bold',
  },
  checkUpdateBtn: {
    marginTop: spaceVertical.semiSmall,
    alignSelf: 'center',
    backgroundColor: '#11162A',
    borderWidth: 1,
    borderColor: '#2E2856',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 2,
  },
  checkUpdateContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  checkUpdateBtnIcon: {
    fontSize: 13,
  },
  checkUpdateBtnText: {
    fontSize: 12.5,
    fontFamily: fontFamily.semiBold,
    color: '#DDD6FE',
    letterSpacing: 0.2,
  },
  versionFooter: {
    marginTop: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  versionFooterText: {
    fontSize: 12,
    fontFamily: fontFamily.medium,
    color: colors.subtitleColor,
  },
  upToDatePill: {
    backgroundColor: '#064E3B',
    borderWidth: 1,
    borderColor: '#059669',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 1.5,
  },
  upToDatePillText: {
    fontSize: 10,
    fontFamily: fontFamily.bold,
    color: '#34D399',
  },
  updateHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(5, 7, 15, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  modalContainer: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#11162A',
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#2E2856',
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 20,
    alignItems: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 12,
  },
  modalCloseButton: {
    position: 'absolute',
    top: 14,
    right: 14,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#1A213D',
    borderWidth: 1,
    borderColor: '#27325C',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  modalCloseIcon: {
    fontSize: 14,
    fontFamily: fontFamily.bold,
    color: '#94A3B8',
    lineHeight: 18,
  },
  modalIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#1E1B4B',
    borderWidth: 1.5,
    borderColor: '#7C3AED',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  modalIconText: {
    fontSize: 26,
  },
  modalTitle: {
    fontSize: 18,
    fontFamily: fontFamily.bold,
    color: colors.titleColor,
    textAlign: 'center',
    marginBottom: 8,
  },
  modalMessage: {
    fontSize: 13,
    fontFamily: fontFamily.medium,
    color: colors.subtitleColor,
    textAlign: 'center',
    lineHeight: 19,
    marginBottom: 20,
    paddingHorizontal: 6,
  },
  modalActionRow: {
    width: '100%',
    flexDirection: 'row',
    gap: 10,
  },
  modalCancelBtn: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#1A213D',
    borderWidth: 1,
    borderColor: '#27325C',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCancelBtnText: {
    fontSize: 13.5,
    fontFamily: fontFamily.semiBold,
    color: '#94A3B8',
  },
  modalUpdateBtn: {
    flex: 2,
    height: 44,
    borderRadius: 12,
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 4,
  },
  modalUpdateBtnIcon: {
    fontSize: 13,
  },
  modalUpdateBtnText: {
    fontSize: 13.5,
    fontFamily: fontFamily.bold,
    color: colors.white,
    letterSpacing: 0.3,
  },
});